spring:
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:15432/pubdb
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'false'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - rate-limit-bucket
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
    - id: getRemoteAddr()
      cache-name: rate-limit-bucket
      url: .*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
      - bandwidths:
        - capacity: 10
          refill-capacity: 1
          time: 30
          unit: seconds
          refill-speed: interval
security:
  api-header-name: "X-API-KEY"
  api-key: ""

# server:
#  port: 443
#  ssl:
#    key-store: "classpath:keystore/pubfinder.p12"
#    key-store-password: ""
#    key-password: ""
#    keyStoreType: "PKCS12"
#    keyAlias: "pubfinder"
